In [1]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np
from sklearn.datasets import load_digits

digits = load_digits()

In [2]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(digits.data,digits.target,test_size=0.3)

In [3]:
lr = LogisticRegression()
lr.fit(x_train,y_train)
lr.score(x_test,y_test)

C:\Users\Aniket Purkayatha\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9666666666666667

In [4]:
svm = SVC()
svm.fit(x_train,y_train)
svm.score(x_test,y_test)

0.987037037037037

In [5]:
rf = SVC()
rf.fit(x_train,y_train)
rf.score(x_test,y_test)

0.987037037037037

***Train test split method is not uniform. Each time the model gives a different accuracy Score. Therefore, we can use K-Fold.split method***

# K-Fold Split


In [8]:
from sklearn.model_selection import KFold
kf = KFold(n_splits=3) # number of splits=3
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [9]:
for train_index,test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index, test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


***Create a function to train and calculate the model score***

In [10]:
def get_score(model,x_train,x_test,y_train,y_test):
    model.fit(x_train,y_train)
    return model.score(x_test,y_test)

In [11]:
get_score(LogisticRegression(),x_train,x_test,y_train,y_test)

C:\Users\Aniket Purkayatha\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9666666666666667

In [13]:
get_score(SVC(),x_train,x_test,y_train,y_test)

0.987037037037037

In [14]:
get_score(RandomForestClassifier(),x_train,x_test,y_train,y_test)

0.9814814814814815

***Create KFold split for digits dataset***

In [15]:
from sklearn.model_selection import StratifiedKFold
folds = StratifiedKFold(n_splits=3)

In [19]:
scores_logistic = []
scores_svm = []
scores_rf = []

for train_index, test_index in folds.split(digits.data,digits.target):
    X_train, X_test, y_train, y_test = digits.data[train_index], digits.data[test_index], \
                                       digits.target[train_index], digits.target[test_index]
    scores_logistic.append(get_score(LogisticRegression(solver='liblinear',multi_class='ovr'), X_train, X_test, y_train, y_test))  
    scores_svm.append(get_score(SVC(gamma='auto'), X_train, X_test, y_train, y_test))
    scores_rf.append(get_score(RandomForestClassifier(n_estimators=40), X_train, X_test, y_train, y_test))

In [20]:
scores_logistic

[0.8948247078464107, 0.9532554257095158, 0.9098497495826378]

In [21]:
scores_svm

[0.3806343906510851, 0.41068447412353926, 0.5125208681135225]

In [22]:
scores_rf

[0.9348914858096828, 0.9482470784641068, 0.9198664440734557]

# Using cross_val_score


***cross_val_score uses stratified KFold by default***

We use cross_val_score to find the best algorithm along with the best parameters that can train a specific model

In [23]:
from sklearn.model_selection import cross_val_score

In [25]:
cross_val_score(LogisticRegression(),digits.data,digits.target,cv=3)

C:\Users\Aniket Purkayatha\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\Aniket Purkayatha\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logis

array([0.92153589, 0.94156928, 0.91652755])

In [26]:
cross_val_score(SVC(gamma='auto'), digits.data, digits.target,cv=3)

array([0.38063439, 0.41068447, 0.51252087])

In [27]:

cross_val_score(RandomForestClassifier(n_estimators=40),digits.data, digits.target,cv=3)

array([0.92821369, 0.93989983, 0.92988314])

***RandomForestClassifier with different Parameters***

In [28]:
scores1 = cross_val_score(RandomForestClassifier(n_estimators=5),digits.data, digits.target, cv=10)
np.average(scores1)

0.8870360024829298

In [29]:
scores2 = cross_val_score(RandomForestClassifier(n_estimators=20),digits.data, digits.target, cv=10)
np.average(scores2)

0.9399068901303538

In [30]:
scores4 = cross_val_score(RandomForestClassifier(n_estimators=40),digits.data, digits.target, cv=10)
np.average(scores4)

0.9415642458100558

***Here we used cross_val_score to fine tune our random forest classifier and figured that having around 40 trees in random forest gives best result.***