# Linear Regression with Multiple Variable

In [1]:
import pandas as pd
import numpy as np
from sklearn import linear_model

In [2]:
df = pd.read_csv("homeprices.csv")
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

**Data Preprocessing (Handle Missing Values)**

In [ ]:
# take median of all the values and insert in the place of NULL value.

In [5]:
import math
median_bedrooms = math.floor(df. bedrooms.median())
median_bedrooms

4

In [8]:
df.bedrooms = df.bedrooms.fillna(median_bedrooms)

In [9]:
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       4.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

**Train Linear Model**

In [12]:
reg = linear_model.LinearRegression()
reg.fit(df[['area','bedrooms','age']],df.price)

LinearRegression()

***price = m1 x area + m2 x bedrooms + m3 x age + b***

In [13]:
reg.coef_

array([  112.06244194, 23388.88007794, -3231.71790863])

In [14]:
reg.intercept_

221323.00186540408

In [15]:
reg.predict([[3000,3,40]])

array([498408.25158031])

In [17]:
112.06244194*3000 + 23388.88007794*3 + -3231.71790863*40 + 221323.00186540408

498408.2515740241

In [18]:
reg.predict([[2500,4,5]])

array([578876.03748933])